### ISSUE TITLE
cannot enter port

### ISSUE THREAD

**Issue by KRIEZIEY** [De-eloper/NjRat-Ghost-Edition#1]
https://user-images.githubusercontent.com/102611940/203412559-9406d8bd-1b37-443a-b9cd-5b3bf1a19820.mp4

**Comment by De-eloper** [comment]
Hey, i'll fix this bug.
It didn't catch me that the backwards value has a limit. Give me few minutes.

**Comment by De-eloper** [comment]
Should be fixed now, try new release. :)

**Comment by KRIEZIEY** [comment]
thanks it work now
